[common]
ColumnsCount = 2048

[column1265]
Lintel = 0
Height = 0
SolidMask = 0
FloorTexture = 27
Orientation = 0
Cubes = [0, 0, 0, 0, 0, 0, 0, 0]

[column1266]
Lintel = 0
Height = 3
SolidMask = 7
FloorTexture = 0
Orientation = 0
Cubes = [148, 399, 398, 0, 0, 0, 0, 0]

[column1267]
Lintel = 0
Height = 0
SolidMask = 0
FloorTexture = 27
Orientation = 0
Cubes = [0, 0, 0, 0, 0, 0, 0, 0]

[column1268]
Lintel = 0
Height = 2
SolidMask = 3
FloorTexture = 0
Orientation = 0
Cubes = [44, 43, 0, 0, 0, 0, 0, 0]

[column1285]
Lintel = 0
Height = 8
SolidMask = 25
FloorTexture = 179
Orientation = 0
Cubes = [148, 0, 0, 481, 160, 0, 0, 0]

[column1286]
Lintel = 0
Height = 8
SolidMask = 97
FloorTexture = 28
Orientation = 0
Cubes = [10, 0, 0, 0, 0, 14, 14, 0]

[column1287]
Lintel = 0
Height = 8
SolidMask = 63
FloorTexture = 29
Orientation = 0
Cubes = [26, 10, 15, 13, 13, 12, 0, 0]

[column1288]
Lintel = 0
Height = 8
SolidMask = 31
FloorTexture = 29
Orientation = 0
Cubes = [26, 10, 15, 13, 12, 0, 0, 0]

[column1289]
Lintel = 0
Height = 8
SolidMask = 49
FloorTexture = 27
Orientation = 0
Cubes = [351, 0, 0, 0, 14, 14, 0, 0]

[column1290]
Lintel = 0
Height = 8
SolidMask = 65
FloorTexture = 27
Orientation = 0
Cubes = [351, 0, 0, 0, 0, 0, 14, 0]

[column1291]
Lintel = 0
Height = 8
SolidMask = 113
FloorTexture = 27
Orientation = 0
Cubes = [351, 0, 0, 0, 14, 14, 14, 0]

[column1292]
Lintel = 0
Height = 8
SolidMask = 97
FloorTexture = 27
Orientation = 0
Cubes = [351, 0, 0, 0, 0, 14, 14, 0]

[column1293]
Lintel = 0
Height = 1
SolidMask = 1
FloorTexture = 28
Orientation = 0
Cubes = [10, 0, 0, 0, 0, 0, 0, 0]

[column1294]
Lintel = 1
Height = 6
SolidMask = 33
FloorTexture = 28
Orientation = 0
Cubes = [10, 0, 0, 0, 0, 14, 0, 0]

[column1295]
Lintel = 1
Height = 6
SolidMask = 63
FloorTexture = 29
Orientation = 0
Cubes = [26, 10, 15, 13, 12, 14, 0, 0]

[column1296]
Lintel = 0
Height = 1
SolidMask = 49
FloorTexture = 27
Orientation = 0
Cubes = [10, 0, 0, 0, 14, 14, 0, 0]

[column1297]
Lintel = 0
Height = 4
SolidMask = 15
FloorTexture = 29
Orientation = 0
Cubes = [26, 15, 13, 12, 0, 0, 0, 0]

[column1298]
Lintel = 5
Height = 6
SolidMask = 63
FloorTexture = 29
Orientation = 0
Cubes = [26, 10, 15, 13, 13, 12, 0, 0]

[column1299]
Lintel = 5
Height = 7
SolidMask = 127
FloorTexture = 29
Orientation = 0
Cubes = [26, 10, 15, 13, 13, 13, 12, 0]

[column1300]
Lintel = 1
Height = 6
SolidMask = 63
FloorTexture = 29
Orientation = 0
Cubes = [26, 15, 13, 13, 12, 13, 0, 0]

[column1301]
Lintel = 0
Height = 3
SolidMask = 7
FloorTexture = 29
Orientation = 0
Cubes = [26, 13, 13, 0, 0, 0, 0, 0]

[column1302]
Lintel = 0
Height = 2
SolidMask = 3
FloorTexture = 29
Orientation = 0
Cubes = [26, 13, 0, 0, 0, 0, 0, 0]

[column1303]
Lintel = 0
Height = 4
SolidMask = 15
FloorTexture = 177
Orientation = 0
Cubes = [192, 152, 151, 151, 0, 0, 0, 0]

[column1304]
Lintel = 0
Height = 4
SolidMask = 15
FloorTexture = 27
Orientation = 0
Cubes = [25, 152, 150, 149, 0, 0, 0, 0]

[column1305]
Lintel = 0
Height = 2
SolidMask = 3
FloorTexture = 27
Orientation = 0
Cubes = [25, 149, 0, 0, 0, 0, 0, 0]

[column1306]
Lintel = 0
Height = 3
SolidMask = 7
FloorTexture = 177
Orientation = 0
Cubes = [192, 152, 149, 0, 0, 0, 0, 0]

[column1307]
Lintel = 0
Height = 2
SolidMask = 3
FloorTexture = 106
Orientation = 0
Cubes = [159, 159, 0, 0, 0, 0, 0, 0]

[column1308]
Lintel = 0
Height = 5
SolidMask = 31
FloorTexture = 27
Orientation = 0
Cubes = [25, 62, 57, 58, 65, 0, 0, 0]

[column1309]
Lintel = 0
Height = 6
SolidMask = 63
FloorTexture = 27
Orientation = 0
Cubes = [25, 62, 57, 58, 65, 149, 0, 0]

[column1310]
Lintel = 0
Height = 1
SolidMask = 33
FloorTexture = 27
Orientation = 0
Cubes = [25, 0, 0, 0, 0, 66, 0, 0]

[column1311]
Lintel = 0
Height = 5
SolidMask = 31
FloorTexture = 27
Orientation = 0
Cubes = [25, 152, 151, 150, 149, 0, 0, 0]

[column1312]
Lintel = 0
Height = 1
SolidMask = 1
FloorTexture = 27
Orientation = 0
Cubes = [149, 0, 0, 0, 0, 0, 0, 0]

[column1313]
Lintel = 0
Height = 5
SolidMask = 31
FloorTexture = 27
Orientation = 0
Cubes = [25, 150, 151, 151, 149, 0, 0, 0]

[column1314]
Lintel = 0
Height = 5
SolidMask = 31
FloorTexture = 27
Orientation = 0
Cubes = [25, 152, 150, 151, 149, 0, 0, 0]

[column1315]
Lintel = 0
Height = 6
SolidMask = 63
FloorTexture = 27
Orientation = 0
Cubes = [25, 152, 151, 151, 150, 149, 0, 0]

[column1316]
Lintel = 0
Height = 2
SolidMask = 3
FloorTexture = 28
Orientation = 0
Cubes = [26, 149, 0, 0, 0, 0, 0, 0]

[column1317]
Lintel = 0
Height = 1
SolidMask = 25
FloorTexture = 29
Orientation = 0
Cubes = [45, 0, 0, 44, 43, 0, 0, 0]

[column1318]
Lintel = 0
Height = 2
SolidMask = 19
FloorTexture = 28
Orientation = 0
Cubes = [26, 16, 0, 0, 43, 0, 0, 0]

[column1319]
Lintel = 0
Height = 3
SolidMask = 23
FloorTexture = 28
Orientation = 0
Cubes = [26, 16, 16, 0, 43, 0, 0, 0]

[column1320]
Lintel = 0
Height = 6
SolidMask = 63
FloorTexture = 29
Orientation = 0
Cubes = [25, 15, 13, 13, 12, 14, 0, 0]

[column1321]
Lintel = 0
Height = 0
SolidMask = 1
FloorTexture = 346
Orientation = 0
Cubes = [482, 0, 0, 0, 0, 0, 0, 0]

